### ISSUE TITLE
Cluster customizer: should `start.d` scripts be run on apply?

### ISSUE THREAD

**Issue by jamesremuscat** [alces-software/clusterware-services#44]
When installing a customization profile post-startup, the `configure.d` and `member-join.d` hooks in that profile are called in turn (where present).

Some profiles also have `start.d` hooks, but these are not called.

This means that, for example, when applying `feature/configure-docker` the user will manually need to `sudo systemctl start docker` before being able to use Docker (since the `start.d` script which otherwise does so is not called).

Should we also be triggering a profile's `start.d` hooks when applying post-startup?

**Comment by mjtko** [comment]
This sounds like a good idea -- I encountered this on a recent software feature profile I was working on.  We should probably also call `node-started` if present.  So on `apply` we should be triggering: `configure`, `start`, `node-started`.
